const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/La_pa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
// TEST: load the real candidate graph with all existing styles, including lazy FBO chunks.
const server=http.createServer((req,res)=>{const n=decodeURI(new URL(req.url,'http://local').pathname).replace(/^\//,'')||'index.html';if(n.includes('..'))return res.writeHead(400).end();let f=path.join(__dirname,'candidate-web',n);if(!fs.existsSync(f))f=path.join(__dirname,'web-base',n);if(!fs.existsSync(f)||!fs.statSync(f).isFile())return res.writeHead(404).end();res.setHeader('Content-Type',n.endsWith('.js')?'text/javascript':n.endsWith('.css')?'text/css':n.endsWith('.html')?'text/html':'application/octet-stream');let data=fs.readFileSync(f);if(n.includes('-0-')&&n.endsWith('.js'))data=Buffer.from(data.toString()+';window.mountReceipt=(props)=>{document.getElementById("root").style.display="none";let el=document.getElementById("receipt-test");if(el)el.remove();el=document.createElement("div");el.id="receipt-test";document.body.append(el);iT.createRoot(el).render(x.createElement(__ReceiptDirections.ReceiptDirectionsPanel,props));};');res.end(data);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let approved=false, saves=0;const calls=[];const row={id:'a'.repeat(32),warehouseId:'w',sourceDocument:'SERIES:2026:FFL_LKB0710',date:'2026-10-07T09:00:00Z',received:16,current:true,boxes:[{code:'FFL_LKB0710_001'}],fbs:true,fbo:true,revision:0,approvalEnabled:true};
await page.route('**/api/v1/**',async r=>{const url=new URL(r.request().url());let body={};if(url.pathname.endsWith('/receipt-channels'))body={enabled:true,rows:[{...row,approval:{available:approved,revision:approved?1:0,...(approved?{changedByName:'Клиент Лукина',changedAt:'2026-10-07T12:00:00Z'}:{})}}]};else if(url.pathname.endsWith('/approval')){const input=r.request().postDataJSON();calls.push(input);if(input.save){saves++;approved=true;}body={approval:{available:input.available}};}else if(url.pathname.endsWith('/history'))body=[];else return r.fulfill({status:401,contentType:'application/json',body:'{}'});return r.fulfill({contentType:'application/json',body:JSON.stringify(body)});});
await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'networkidle'});const assets=JSON.parse(fs.readFileSync(__dirname+'/web-changes.json')).filter(n=>n.endsWith('.js'));for(const n of assets)await page.evaluate(n=>import('/'+n),n);await page.evaluate(()=>window.mountReceipt({session:{accessToken:'test',user:{roleCodes:['CLIENT']}},fixedClientId:'c'}));
await page.getByRole('switch').waitFor();assert.equal(await page.getByRole('switch').isChecked(),false);assert.equal(await page.getByLabel('ФБС').count(),0);
await page.getByRole('switch').click();await page.getByRole('button',{name:'Подтвердить',exact:true}).waitFor();assert.equal(saves,0);await page.getByRole('button',{name:'Отмена',exact:true}).click();assert.equal(saves,0);
await page.getByRole('switch').click();await page.getByRole('button',{name:'Подтвердить',exact:true}).click();await page.getByText('Клиент Лукина',{exact:false}).waitFor();assert.equal(saves,1);assert.equal(await page.getByRole('switch').isChecked(),true);assert.equal(await page.getByRole('switch').isDisabled(),true);assert.equal(calls.at(-1).clientId,'c');assert.equal(calls.at(-1).warehouseId,'w');
assert.deepEqual(errors,[]);await page.screenshot({path:__dirname+'/client-confirmed.png',fullPage:true});console.log('PASS actual client UI: preview, cancel, confirmation, author/time and no revocation');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
