import { useEffect, useRef, useState } from 'react';
import type { AuthSession } from '../../lib/api';

type Approval={available:boolean;revision:number;changedAt?:string;changedByName?:string};
type Receipt = {id:string;warehouseId:string;sourceDocument:string;date:string;received:number;current:boolean;boxCount?:number;boxes:{code:string}[];fbs:boolean;fbo:boolean;revision:number;approvalEnabled?:boolean;approval?:Approval};
type Change = {id:string;clientId:string;fbs:boolean;fbo:boolean;revision:number};
// FIX: receipt controls have their own date filter and never mutate flags until preview/save succeeds.
export function ReceiptDirectionsPanel({session,fixedClientId}:{session:AuthSession;fixedClientId?:string}) {
  const [client,setClient]=useState(fixedClientId||'');
  const [clients,setClients]=useState<{id:string;name:string}[]>([]);
  const [from,setFrom]=useState(()=>new Date(Date.now()-30*86400000).toISOString().slice(0,10));
  const [to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
  const [rows,setRows]=useState<Receipt[]>([]),[enabled,setEnabled]=useState(false);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [preview,setPreview]=useState<{change:Change;available:number;protectedQuantity:number;excludedQuantity:number}|null>(null);
  const [assignment,setAssignment]=useState<{id:string;boxCode:string;checked?:{series:string;fbs:boolean;fbo:boolean}}|null>(null);
  const [approval,setApproval]=useState<{row:Receipt;available:boolean}|null>(null);
  const [filter,setFilter]=useState('all');
  const [histories,setHistories]=useState<Record<string,Array<{createdAt:string;payload:{next:Approval}}>>>({});
  const generation=useRef(0);
  const [receiptBoxes,setReceiptBoxes]=useState<Record<string,{code:string}[]>>({});
  const boxReads=useRef(new Set<string>());
  const admin=session.user.roleCodes.some(r=>r==='ADMIN'||r==='OWNER');
  async function api(url:string,body?:unknown){const response=await fetch(`/api/v1${url}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${session.accessToken}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(Array.isArray(data.message)?data.message.join('; '):data.message||'Не удалось выполнить операцию.');return data;}
  useEffect(()=>{if(admin&&!fixedClientId)void api('/clients').then(setClients).catch(e=>setMessage(e.message));},[session.accessToken,admin,fixedClientId]);
  async function load(){const current=++generation.current;setPreview(null);setAssignment(null);setRows([]);setReceiptBoxes({});if(!client)return;setBusy(true);setMessage('');try{const data=await api(`/warehouse/receipt-channels?clientId=${encodeURIComponent(client)}&from=${from}&to=${to}&summary=1`);if(current===generation.current){setRows(data.rows);setEnabled(data.enabled);}}catch(e){if(current===generation.current)setMessage(String((e as Error).message));}finally{if(current===generation.current)setBusy(false);}}
  useEffect(()=>{setApproval(null);setHistories({});void load();return()=>{generation.current++;};},[client,from,to,session.accessToken,admin]);
  // FIX: contents load on expansion; stale replies cannot cross client/filter changes.
  async function loadBoxes(row:Receipt){
    if(row.boxCount===undefined||receiptBoxes[row.id]||boxReads.current.has(row.id))return;
    const current=generation.current;boxReads.current.add(row.id);
    try{const data=await api(`/warehouse/receipt-channels?clientId=${encodeURIComponent(client)}&from=${from}&to=${to}&receiptId=${row.id}`);
      if(current===generation.current){const found=data.rows.find((r:Receipt)=>r.id===row.id);if(found)setReceiptBoxes(b=>({...b,[row.id]:found.boxes}));}
    }catch(e){if(current===generation.current)setMessage((e as Error).message);}finally{boxReads.current.delete(row.id);}
  }
  async function change(row:Receipt,channel:'fbs'|'fbo',value:boolean){setBusy(true);setMessage('');setPreview(null);const change={id:row.id,clientId:client,fbs:row.fbs,fbo:row.fbo,revision:row.revision,[channel]:value};try{const result=await api('/warehouse/receipt-channels/preview',change);setPreview({...result,change});}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function save(){if(!preview)return;setBusy(true);try{await api('/warehouse/receipt-channels',preview.change);await load();setMessage('Направления приёмки сохранены. Остатки WB пересчитываются при синхронизации.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function assign(save:boolean){if(!assignment)return;setBusy(true);setMessage('');try{const data=await api('/warehouse/receipt-channels/assign-box',{id:assignment.id,clientId:client,boxCode:assignment.boxCode,save});if(save){await load();setMessage('Короб отнесён к выбранной приёмке. Штрихкод короба сохранён.');}else setAssignment({...assignment,checked:data});}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function confirmApproval(row:Receipt,available:boolean,save:boolean){const version=generation.current;setBusy(true);setMessage('');try{await api('/warehouse/receipt-channels/approval',{clientId:client,warehouseId:row.warehouseId,id:row.id,available,revision:row.approval?.revision??0,save});if(version!==generation.current)return;if(save){setApproval(null);await load();setMessage(available?'Доступ в остатках включён. Подтверждение сохранено в истории.':'Приёмка возвращена на согласование. Хранение продолжает начисляться.');}else setApproval({row,available});}catch(e){if(version===generation.current)setMessage((e as Error).message);}finally{if(version===generation.current||save)setBusy(false);}}
  async function history(row:Receipt){try{const result=await api(`/warehouse/receipt-channels/history?clientId=${encodeURIComponent(client)}&warehouseId=${encodeURIComponent(row.warehouseId)}&id=${row.id}`);setHistories(h=>({...h,[row.id]:result}));}catch(e){setMessage((e as Error).message);}}
  async function download(row:Receipt){setBusy(true);try{const response=await fetch(`/api/v1/warehouse/receipt-channels/file.xlsx?clientId=${encodeURIComponent(client)}&warehouseId=${encodeURIComponent(row.warehouseId)}&id=${row.id}`,{headers:{Authorization:`Bearer ${session.accessToken}`}});if(!response.ok)throw Error('Не удалось скачать файл приёмки.');const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`Приёмка-${row.sourceDocument.replace(/^SERIES:\d{4}:/,'')}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  const visible=rows.filter(r=>filter==='all'||(filter==='approved')===(r.approval?.available!==false));
  return <section className="surface-card receipt-directions" style={{padding:16,marginBottom:16}}><h3>Приёмки · сверка и доступ в остатках</h3>
    <p>До подтверждения сверки товар не доступен в остатках, сборке ФБО/ФБС и передаче остатков маркетплейсам. Хранение начисляется с фактической приёмки, включая время согласования.</p>
    <div className="warehouse-drafts__toolbar">
      {!fixedClientId&&<label>Клиент<select disabled={busy} value={client} onChange={e=>setClient(e.target.value)}><option value="">Выберите клиента</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
      <label>С даты<input disabled={busy} type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>По дату<input disabled={busy} type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>
      <button type="button" disabled={!client||busy} onClick={()=>void load()}>Обновить</button>
    </div>
    {message&&<p role="status">{message}</p>}{busy&&<p>Проверка…</p>}
    {client&&!busy&&!enabled&&<p>Настройка направлений пока не включена.</p>}
    {enabled&&<><div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'16px 0'}}>{[['all','Все приёмки'],['pending','На согласовании'],['approved','Доступны в остатках']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div>
    {approval&&<div className="surface-card" role="region" aria-label="Подтверждение доступа" style={{padding:16,marginBottom:16}}><strong>{approval.available?'Подтвердить сверку и открыть доступ в остатках?':'Отключить доступ в остатках?'}</strong><p>{approval.row.sourceDocument.replace(/^SERIES:\d{4}:/,'')} · {approval.row.received} шт. Решение будет записано с вашим именем и временем. Хранение продолжает начисляться.</p><button disabled={busy} onClick={()=>void confirmApproval(approval.row,approval.available,true)}>Подтвердить</button> <button disabled={busy} onClick={()=>setApproval(null)}>Отмена</button></div>}
    <div style={{overflowX:'auto'}}><table><thead><tr><th>Приёмка / короба</th><th>Принято, шт.</th><th>Доступ в остатках</th><th>Направления</th><th>Хранение</th></tr></thead><tbody>{visible.map(row=><tr key={row.id}><td><strong>{row.sourceDocument.replace(/^SERIES:\d{4}:/,'')}</strong><div>{new Date(row.date).toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow'})}</div><details onToggle={e=>{if(e.currentTarget.open)void loadBoxes(row);}}><summary>{row.boxCount??row.boxes.length} коробов</summary>{row.boxCount!==undefined&&!receiptBoxes[row.id]&&<span>Загрузка коробов…</span>}{(receiptBoxes[row.id]??row.boxes).map(b=><div key={b.code}>{b.code}</div>)}</details><button disabled={busy} onClick={()=>void download(row)}>Файл приёмки</button>{admin&&<details><summary>Действия с коробами</summary><button disabled={busy||!!preview||!!assignment||!!approval} onClick={()=>setAssignment({id:row.id,boxCode:''})}>Добавить ошибочно названный короб</button></details>}</td><td>{row.received}</td><td><label style={{display:'flex',gap:8,alignItems:'center',fontWeight:700}}><input role="switch" type="checkbox" aria-label={`Доступ в остатках ${row.sourceDocument}`} checked={row.approval?.available!==false} disabled={!row.approvalEnabled||busy||!!preview||!!assignment||!!approval||(!admin&&row.approval?.available!==false)} onChange={e=>void confirmApproval(row,e.target.checked,false)}/>{row.approval?.available===false?'На согласовании':'Доступна в остатках'}</label>{row.approval?.changedAt?<div>{row.approval.changedByName}<br/>{new Date(row.approval.changedAt).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})} МСК</div>:<div>{row.approval?.available===false?'Ожидает подтверждения клиента':'Доступ сохранён при включении согласования'}</div>}<details onToggle={e=>{if(e.currentTarget.open)void history(row);}}><summary>История изменений</summary>{histories[row.id]?.length?histories[row.id].map((h,i)=><div key={i}>{h.payload.next.available?'Доступ включён':'Доступ выключен'} · {h.payload.next.changedByName} · {new Date(h.createdAt).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})} МСК</div>):<div>Изменений доступа нет.</div>}</details></td><td>{(['fbs','fbo'] as const).map(channel=><label key={channel} style={{display:'flex',gap:7,padding:4}}><input aria-label={`${channel.toUpperCase()} ${row.sourceDocument}`} type="checkbox" checked={row[channel]} disabled={!admin||busy||!!preview||!!assignment||!!approval} onChange={e=>void change(row,channel,e.target.checked)}/>{channel==='fbs'?'ФБС':'ФБО'}</label>)}{row.approval?.available===false&&<small>После согласования</small>}</td><td><strong>Начисляется</strong><div>С {new Date(row.date).toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow'})}</div></td></tr>)}</tbody></table>{!visible.length&&<p>Приёмок по выбранному фильтру нет.</p>}</div></>}
    {assignment&&<div role="region" aria-label="Привязка короба"><label>Номер короба<input value={assignment.boxCode} disabled={busy} onChange={e=>setAssignment({...assignment,boxCode:e.target.value,checked:undefined})}/></label>{assignment.checked?<><p>Короб будет относиться к {assignment.checked.series.replace(/^SERIES:\d{4}:/,'')}. ФБС: {assignment.checked.fbs?'разрешён':'выключен'}, ФБО: {assignment.checked.fbo?'разрешён':'выключен'}.</p><button disabled={busy} onClick={()=>void assign(true)}>Подтвердить привязку</button></>:<button disabled={busy||!assignment.boxCode.trim()} onClick={()=>void assign(false)}>Проверить короб</button>}<button disabled={busy} onClick={()=>setAssignment(null)}>Отмена</button></div>}
    {preview&&<div role="region" aria-label="Проверка направлений" className="surface-card" style={{padding:16}}><strong>Сохранить: ФБС {preview.change.fbs?'разрешён':'выключен'}, ФБО {preview.change.fbo?'разрешён':'выключен'}</strong><p>Доступно на складе: {preview.available} шт. Под существующие заказы ФБС: {preview.protectedQuantity} шт. Исключается из новых продаж ФБС: {preview.excludedQuantity} шт.</p><button disabled={busy} onClick={()=>void save()}>Сохранить направления</button><button disabled={busy} onClick={()=>setPreview(null)}>Отмена</button></div>}
  </section>;
}
