const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/La_pa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
// TEST: load the real candidate graph with all existing styles, including lazy FBO chunks.
const server=http.createServer((req,res)=>{const n=decodeURI(new URL(req.url,'http://local').pathname).replace(/^\//,'')||'index.html';if(n.includes('..'))return res.writeHead(400).end();let f=path.join(__dirname,'candidate-web',n);if(!fs.existsSync(f))f=path.join(__dirname,'web-base',n);if(!fs.existsSync(f)||!fs.statSync(f).isFile())return res.writeHead(404).end();res.setHeader('Content-Type',n.endsWith('.js')?'text/javascript':n.endsWith('.css')?'text/css':n.endsWith('.html')?'text/html':'application/octet-stream');let data=fs.readFileSync(f);if(n.includes('-0-')&&n.endsWith('.js'))data=Buffer.from(data.toString()+';window.mountWarehouse=(session)=>{document.getElementById("root").style.display="none";const el=document.createElement("div");document.body.append(el);iT.createRoot(el).render(x.createElement(p5,{session}));};window.testWarehouseNav=a2;');res.end(data);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const requests=[];await page.route('**/api/v1/**',async r=>{const url=new URL(r.request().url());requests.push({path:url.pathname,method:r.request().method()});let data=[];if(url.pathname==='/api/v1/clients')data=[{id:'own',name:'Лукин',onlineReceiptVisibleToClient:true}];else if(url.pathname.endsWith('/online-receipts'))data={boxes:[],deletedBoxes:[],generatedAt:new Date().toISOString()};else if(url.pathname.endsWith('/goods-arrivals/summary'))data={estimatedRub:0};else if(url.pathname.endsWith('/receipt-channels'))data={enabled:true,rows:[]};else if(url.pathname.includes('auth'))return r.fulfill({status:401,contentType:'application/json',body:'{}'});return r.fulfill({contentType:'application/json',body:JSON.stringify(data)});});
await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'networkidle'});const assets=JSON.parse(fs.readFileSync(__dirname+'/web-changes.json')).filter(n=>n.endsWith('.js'));for(const n of assets)await page.evaluate(n=>import('/'+n),n);await page.evaluate(()=>{const user={id:'client',roleCodes:['CLIENT'],permissionCodes:['stock:read'],clientIds:['own'],writableClientIds:['own']};if(!window.testWarehouseNav(user,{id:'warehouse',audience:'internal',permissions:['warehouse:read']}))throw Error('Navigation hidden');window.mountWarehouse({accessToken:'test',user});});
await page.locator('.warehouse-topic-tile').first().waitFor();assert.equal(await page.locator('.warehouse-topic-tile').count(),4);
await page.screenshot({path:__dirname+'/client-warehouse.png',fullPage:true});
for(const id of ['online-receipts','arrivals','receipt-batches','shipment-history']){await page.locator('.warehouse-topic-tile--'+id).click();await page.waitForTimeout(350);assert.equal(await page.getByRole('button',{name:'Записать приход',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Сформировать счет ППР',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Обновить историю',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Завершить приемку',exact:true}).count(),0);await page.getByRole('button',{name:'Разделы склада',exact:true}).click();}
assert.deepEqual(errors,[]);assert.equal(requests.filter(q=>q.method!=='GET').length,0);assert.ok(requests.some(q=>q.path.endsWith('/shipment-history')));console.log('PASS actual client warehouse: four screens, navigation, no mutation controls or requests');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
