const fs=require('fs'),path=require('path'),ts=require('../service-menu-tiles/wms/node_modules/typescript'),r=__dirname;
const graph=JSON.parse(fs.readFileSync(r+'/web-graph.json')),files=Object.fromEntries(graph.map(n=>[n,fs.readFileSync(r+'/web-base/'+n,'utf8')])),fn=JSON.parse(fs.readFileSync(r+'/functions.json'));
function rep(s,a,b){if(s.split(a).length!==2)throw Error('Anchor '+a);return s.replace(a,b);}
function patch(key,change){const m=fn[key],old=fs.readFileSync(r+'/fn-'+key+'.js','utf8'),s=change(old);files[m.file]=rep(files[m.file],old,s);fs.writeFileSync(r+'/patched-'+key+'.js',s);}
const allowed='["online-receipts","arrivals","receipt-batches","shipment-history"]';
patch('navigation',s=>rep(rep(s,'R5(t)&&n.audience==="internal"','R5(t)&&n.audience==="internal"&&n.id!=="warehouse"'),'?!1:n.permissions.length','?!1:n.id==="warehouse"&&R5(t)?t.permissionCodes.includes("stock:read"):n.permissions.length'));
patch('warehouse',s=>{s=rep(s,'const[r,i]=x.useState(null);','const[topic,i]=x.useState(null),clientView=n.user.roleCodes.includes("CLIENT"),r=clientView&&topic&&!'+allowed+'.includes(topic)?null:topic;');s=rep(s,'g5(n.user,"stock:write")?','(g5(n.user,"stock:write")||(clientView&&g5(n.user,"stock:read")))?');s=rep(s,'e.jsx(m5,{onOpen:i})','e.jsx(m5,{onOpen:i,clientView})');return rep(s,'e.jsx(LC,{session:n})','e.jsx(LC,{session:n,readOnly:clientView})');});
patch('topics',s=>rep(rep(rep(s,'function m5({onOpen:t})','function m5({onOpen:t,clientView=false})'),'children:n.map(',`children:n.filter(topic=>!clientView||${allowed}.includes(topic.id)).map(`),'children:s.description','children:clientView&&s.id==="arrivals"?"Просматривайте зарегистрированные поступления товара.":s.description'));
function hide(s,tags){const ast=ts.createSourceFile('f.js',s,99,true,1),edits=[];function walk(n){if(ts.isCallExpression(n)&&['e.jsx','e.jsxs'].includes(n.expression.getText(ast))&&ts.isStringLiteral(n.arguments[0])){const str=n.getText(ast),tag=n.arguments[0].text;if(tags.some(([t,marker])=>tag===t&&str.includes(marker)))edits.push(n.getStart(ast));}ts.forEachChild(n,walk);}walk(ast);for(const start of edits.sort((a,b)=>b-a))s=s.slice(0,start)+'!readOnly&&'+s.slice(start);if(edits.length!==tags.length)throw Error('Control count '+edits.length);return s;}
patch('arrivals',s=>{s=rep(s,'function W8({session:t}){','function W8({session:t}){const readOnly=t.user.roleCodes.includes("CLIENT");');s=rep(s,'U.preventDefault(),E("");','U.preventDefault();if(readOnly)return;E("");');s=rep(s,'async function q(){','async function q(){if(readOnly)return;');s=rep(s,'async function $(U){','async function $(U){if(readOnly)return;');return hide(s,[['label','Дата прихода'],['label','Мешки'],['label','Короба'],['label','Комментарий'],['button','Записать приход'],['button','Сформировать счет ППР'],['button','title:"Удалить"']]);});
patch('shipments',s=>{s=rep(s,'function h5({session:t}){','function h5({session:t}){const readOnly=t.user.roleCodes.includes("CLIENT");');s=rep(s,'async function C(){','async function C(){if(readOnly)return;');return hide(s,[['button','Обновить историю']]);});
const rename=Object.fromEntries(graph.filter(n=>n.endsWith('.js')).map(n=>[path.basename(n),path.basename(n,'.js')+'-clientwarehouse.js'])),changes=[];
for(const n of graph){let s=files[n];for(const [a,b]of Object.entries(rename).sort((a,b)=>b[0].length-a[0].length))s=s.split(a).join(b);const dest=n.endsWith('.js')?'assets/'+rename[path.basename(n)]:n;if(n.endsWith('.js')&&ts.createSourceFile(dest,s,99,true,1).parseDiagnostics.length)throw Error('Invalid '+dest);const p=r+'/candidate-web/'+dest;fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,s);changes.push(dest);}
fs.writeFileSync(r+'/web-changes.json',JSON.stringify(changes));console.log('Patched five functions, preserved runtime notification targets and whole graph');
