package pro.logoff.wms.fbsassembly;

import android.app.*;import android.os.*;import android.provider.Settings;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class MainActivity extends Activity{
 final String base="https://wms.logoff.pro/api/v1";String token="";final ArrayList<String> stationIds=new ArrayList<>();Spinner station;EditText code,login,password;TextView result,prompt,stationLabel;boolean busy=false;android.content.SharedPreferences prefs;
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);prefs=getSharedPreferences("fbs",0);station=findViewById(R.id.station);code=findViewById(R.id.code);login=findViewById(R.id.login);password=findViewById(R.id.password);result=findViewById(R.id.result);prompt=findViewById(R.id.prompt);stationLabel=findViewById(R.id.stationLabel);login.setText(prefs.getString("login",""));findViewById(R.id.loginButton).setOnClickListener(v->login());code.setOnEditorActionListener((v,a,e)->{if(a==EditorInfo.IME_ACTION_DONE||(e!=null&&e.getKeyCode()==KeyEvent.KEYCODE_ENTER)){scan();return true;}return false;});code.setOnKeyListener((v,k,e)->{if(k==KeyEvent.KEYCODE_ENTER&&e.getAction()==KeyEvent.ACTION_UP){scan();return true;}return false;});}
 void login(){String l=login.getText().toString().trim(),p=password.getText().toString();if(l.isEmpty()||p.isEmpty()){show("Введите логин и пароль.");return;}show("Подключение к WMS…");run("/auth/login","POST",new JSONObject(map("email",l,"password",p)).toString(),j->{token=j.optString("accessToken");prefs.edit().putString("login",l).apply();loadStations();});}
 void loadStations(){run("/marketplace-connections/fbs/print-stations","GET",null,j->{try{JSONArray a=j.optJSONArray("items");if(a==null)a=new JSONArray(j.toString());stationIds.clear();ArrayList<String> names=new ArrayList<>();String saved=prefs.getString("stationId","");int selected=0;for(int i=0;i<a.length();i++){JSONObject s=a.getJSONObject(i);stationIds.add(s.getString("id"));if(saved.equals(s.getString("id")))selected=i;names.add((s.optBoolean("online")?"● ":"○ ")+s.getString("name")+" · "+s.getString("printerModel")+" · "+s.getInt("labelWidthMm")+"×"+s.getInt("labelHeightMm"));}final int pos=selected;runOnUiThread(()->{if(names.isEmpty()){show("Нет печатных станций. Создайте станцию в WMS.");return;}station.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));station.setSelection(pos);station.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View v,int n,long id){prefs.edit().putString("stationId",stationIds.get(n)).apply();focus();}});login.setVisibility(View.GONE);password.setVisibility(View.GONE);findViewById(R.id.loginButton).setVisibility(View.GONE);station.setVisibility(View.VISIBLE);stationLabel.setVisibility(View.VISIBLE);prompt.setVisibility(View.VISIBLE);code.setVisibility(View.VISIBLE);show("Готово. Отсканируйте КИЗ — две этикетки будут напечатаны автоматически.");focus();});}catch(Exception x){show("Ошибка станций: "+x.getMessage());}});}
 void scan(){if(busy)return;int pos=station.getSelectedItemPosition();String value=code.getText().toString().replace("\r","").replace("\n","").trim();if(pos<0||value.length()<6){focus();return;}busy=true;code.setEnabled(false);show("Ищу заказ и ставлю две этикетки в очередь…");String device=android.os.Build.MODEL+":"+Settings.Secure.getString(getContentResolver(),Settings.Secure.ANDROID_ID);run("/marketplace-connections/fbs/web-order-assembly/scan","POST",new JSONObject(map("code",value,"stationId",stationIds.get(pos),"deviceCode",device)).toString(),j->runOnUiThread(()->{busy=false;code.setEnabled(true);code.setText("");if(j.optString("printJobId").isEmpty())show("Заказ найден, но печатная станция не получила задание.");else show("✓ ДВЕ ЭТИКЕТКИ ПЕРЕДАНЫ НА ПЕЧАТЬ\nЗаказ №"+j.optString("orderId")+"\nЗаявка №"+String.format("%06d",j.optInt("requestNumber"))+"\nСклад: "+j.optString("warehouseName"));focus();}));}
 void focus(){code.postDelayed(()->{code.requestFocus();getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);},80);}
 interface Done{void ok(JSONObject j);}Map<String,Object>map(Object...v){Map<String,Object>m=new HashMap<>();for(int i=0;i<v.length;i+=2)m.put(String.valueOf(v[i]),v[i+1]);return m;}
 void run(String path,String method,String body,Done done){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(base+path).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(25000);c.setRequestMethod(method);c.setRequestProperty("Content-Type","application/json");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if(body!=null){c.setDoOutput(true);c.getOutputStream().write(body.getBytes(StandardCharsets.UTF_8));}int status=c.getResponseCode();InputStream in=status<400?c.getInputStream():c.getErrorStream();String text=new String(in.readAllBytes(),StandardCharsets.UTF_8);if(status>=400){JSONObject e=new JSONObject(text);Object msg=e.opt("message");throw new Exception(msg instanceof JSONArray?((JSONArray)msg).join("; "):String.valueOf(msg));}JSONObject response=text.trim().startsWith("[")?new JSONObject().put("items",new JSONArray(text)):new JSONObject(text);done.ok(response);}catch(Exception x){runOnUiThread(()->{busy=false;code.setEnabled(true);code.setText("");show("ОШИБКА\n"+x.getMessage());focus();});}}).start();}
 void show(String s){runOnUiThread(()->result.setText(s));}
}
