import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { BillingService } from '../src/modules/billing/billing.service';
import { ClientScopeService } from '../src/modules/auth/client-scope.service';
const user:any={id:'owner',permissionCodes:['billing:write'],clientScopeMode:'LIMITED',clientIds:['client'],writableClientIds:['client'],activeWarehouseId:'w',writableWarehouseIds:['w']};
function fixture(options:{total?:number;paid?:number;status?:string;correction?:number;closed?:boolean;comment?:string}={}) {
 const payments:any[]=[];
 const invoice:any={id:'invoice',number:'INV-TEST',clientId:'client',warehouseId:'w',status:options.status??'ISSUED',totalRub:options.total??550535.37,paidRub:options.paid??450000,issuedAt:new Date('2026-09-30'),paidAt:null,comment:options.comment??null,payments};
 const tx:any={billingInvoice:{findUnique:vi.fn(async()=>({...invoice,payments:[...payments]})),findUniqueOrThrow:vi.fn(async()=>({...invoice,payments:[...payments]})),update:vi.fn(async(args:any)=>{Object.assign(invoice,args.data);return{...invoice,payments:[...payments]};})},billingPayment:{create:vi.fn(async(args:any)=>{const p={id:'p'+payments.length,...args.data};payments.push(p);return p;})},clientNotificationPreference:{findUnique:vi.fn(async()=>({isEnabled:false}))},clientNotification:{create:vi.fn()},$queryRaw:vi.fn(async(query:any)=>{const sql=Array.isArray(query)?query.join(''):query.sql;if(sql.includes('pg_advisory'))return[];if(sql.includes('BillingInvoiceCorrection'))return options.correction?[{amountRub:options.correction}]:[];if(sql.includes('BillingPeriodClose'))return options.closed?[{id:'closed'}]:[];throw Error('Unexpected query');})};
 let queue=Promise.resolve();
 const db:any={...tx,$transaction:vi.fn(async(fn:any)=>{let release!:()=>void;const previous=queue;queue=new Promise<void>(resolve=>{release=resolve;});await previous;try{return await fn(tx);}finally{release();}})};
 return {tx,invoice,payments,service:new BillingService(db,new ClientScopeService())};
}
beforeEach(()=>{vi.stubEnv('WMS_BILLING_INVOICE_PAID_RECEIPT_ENABLED','true');vi.stubEnv('WMS_BILLING_PERIOD_CLOSE_ENABLED','true');});
afterEach(()=>vi.unstubAllEnvs());
// TEST: reproduces the reported rejection; closing from the card must record only the unpaid remainder.
it('records the remaining 100535.37 as an actual payment and closes the invoice',async()=>{const{service,payments}=fixture();const updated=await service.updateInvoiceStatus('invoice',{status:'PAID'},user);expect(payments).toHaveLength(1);expect(payments[0]).toMatchObject({amountRub:100535.37,clientId:'client',invoiceId:'invoice',createdByUserId:'owner'});expect(updated).toMatchObject({status:'PAID',paidRub:550535.37});expect(updated.payments).toHaveLength(1);});
it('records the full amount when nothing was paid',async()=>{const{service,payments}=fixture({total:1200,paid:0});await service.updateInvoiceStatus('invoice',{status:'PAID'},user);expect(payments[0].amountRub).toBe(1200);});
// TEST: simultaneous clicks and retry after a lost response cannot record duplicate cash.
it('is idempotent under concurrent clicks and response retries',async()=>{const{service,payments,tx}=fixture();await Promise.all([service.updateInvoiceStatus('invoice',{status:'PAID'},user),service.updateInvoiceStatus('invoice',{status:'PAID'},user)]);await service.updateInvoiceStatus('invoice',{status:'PAID'},user);expect(payments).toHaveLength(1);expect(tx.billingInvoice.update).toHaveBeenCalledTimes(1);});
it('pays the corrected effective total without changing the original invoice amount',async()=>{const{service,payments,invoice}=fixture({total:1000,paid:100,correction:-200});await service.updateInvoiceStatus('invoice',{status:'PAID'},user);expect(payments[0].amountRub).toBe(700);expect(invoice).toMatchObject({totalRub:1000,paidRub:800,status:'PAID'});});
it('keeps partial incoming payment partial',async()=>{const{service,payments,invoice}=fixture({total:1000,paid:0});await service.createPayment({invoiceId:'invoice',amountRub:450},user);expect(payments).toHaveLength(1);expect(invoice).toMatchObject({paidRub:450,status:'ISSUED'});});
it('does not truncate a credit when an already paid invoice is closed again',async()=>{const{service,payments,invoice}=fixture({total:1000,paid:1200,status:'PAID'});await service.updateInvoiceStatus('invoice',{status:'PAID'},user);expect(payments).toHaveLength(0);expect(invoice.paidRub).toBe(1200);});
it.each([{status:'CANCELLED'},{comment:'Объединено в счёт INV-MERGED.'}])('rejects cancelled or merged sources before recording payment: %j',async options=>{const{service,payments}=fixture(options);await expect(service.updateInvoiceStatus('invoice',{status:'PAID'},user)).rejects.toThrow();expect(payments).toHaveLength(0);});
it('allows paying an issued invoice in a closed period',async()=>{const{service,payments}=fixture({closed:true});await service.updateInvoiceStatus('invoice',{status:'PAID'},user);expect(payments).toHaveLength(1);});
it('does not issue a late draft in a closed period through full payment',async()=>{const{service,payments}=fixture({closed:true,status:'DRAFT'});await expect(service.updateInvoiceStatus('invoice',{status:'PAID'},user)).rejects.toThrow('Поздний счёт');expect(payments).toHaveLength(0);});
it('retains the existing default-off guard',async()=>{vi.stubEnv('WMS_BILLING_INVOICE_PAID_RECEIPT_ENABLED','false');const{service,payments}=fixture();await expect(service.updateInvoiceStatus('invoice',{status:'PAID'},user)).rejects.toThrow('Сначала зарегистрируйте');expect(payments).toHaveLength(0);});
it('denies another client or branch',async()=>{const{service,payments}=fixture();await expect(service.updateInvoiceStatus('invoice',{status:'PAID'},{...user,writableClientIds:[]})).rejects.toThrow('Нет доступа');await expect(service.updateInvoiceStatus('invoice',{status:'PAID'},{...user,activeWarehouseId:'other'})).rejects.toThrow('другому филиалу');expect(payments).toHaveLength(0);});
