import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { createFboCompositionCharges } from './fbo-processing-pricing.charges';
const catalog = [{ id: 'cut3', name: 'Отрез 3 м', code: 'NOM_ОТРЕЗ_3М', unit: 'PIECE', isActive: true }, { id: 'cut10', name: 'Отрез 10 м', code: 'NOM_ОТРЕЗ_10М', unit: 'PIECE', isActive: true }];
const definition = { common: [], variants: catalog.map((s, i) => ({ name: s.name, skuIds: ['sku' + i], services: [{ serviceId: s.id, priceRub: i ? '60' : '30', multiplier: '1', taxMode: 'ADD_6_PERCENT' }] })) };
function fixture() { const tx: any = { $queryRaw: vi.fn().mockResolvedValue([{ id: 'tariff', createdAt: new Date('2026-10-05'), definition }]), billingCharge: { findFirst: vi.fn().mockResolvedValue(null), create: vi.fn() }, billingService: { findMany: vi.fn().mockResolvedValue(catalog) } }; const input = { request: { id: 'request', clientId: 'client' }, user: { id: 'owner' }, serviceDate: new Date('2026-10-06'), processedUnits: 3, packages: [{ items: [{ skuId: 'sku0', quantity: 2 }, { skuId: 'sku1', quantity: 1 }] }] }; return { tx, input }; }
beforeEach(() => vi.stubEnv('WMS_FBO_PROCESSING_PRICING_ENABLED', 'true'));
afterEach(() => vi.unstubAllEnvs());
// TEST: reproduce incorrect universal cut pricing; each actual SKU uses its own price.
it('charges actual cut variants with separate snapshots and existing tax rounding', async () => { const { tx, input } = fixture(); expect(await createFboCompositionCharges(tx, input)).toBe(true); expect(tx.billingCharge.create.mock.calls.map((c: any) => [c[0].data.serviceId, c[0].data.quantity, c[0].data.totalRub])).toEqual([['cut3', '2.000', '63.83'], ['cut10', '1.000', '63.83']]); });
it('does not touch sold/default-off billing or run new SQL', async () => { vi.stubEnv('WMS_FBO_PROCESSING_PRICING_ENABLED', 'false'); const { tx, input } = fixture(); expect(await createFboCompositionCharges(tx, input)).toBe(false); expect(tx.$queryRaw).not.toHaveBeenCalled(); });
it('does not recalculate old work', async () => { const { tx, input } = fixture(); input.serviceDate = new Date('2026-10-04'); expect(await createFboCompositionCharges(tx, input)).toBe(false); expect(tx.billingCharge.create).not.toHaveBeenCalled(); });
it('leaves unconfigured clients on the existing path', async () => { const { tx, input } = fixture(); tx.$queryRaw.mockResolvedValue([]); expect(await createFboCompositionCharges(tx, input)).toBe(false); expect(tx.billingCharge.create).not.toHaveBeenCalled(); });
it('repeated closing keeps existing composition charges', async () => { const { tx, input } = fixture(); tx.billingCharge.findFirst.mockResolvedValue({ sourceKey: 'fulfillment-fbo-composition:request:tariff:variant-0:cut3' }); expect(await createFboCompositionCharges(tx, input)).toBe(true); expect(tx.billingCharge.create).not.toHaveBeenCalled(); });
it('never adds composition charges to previously billed processing', async () => { const { tx, input } = fixture(); tx.billingCharge.findFirst.mockResolvedValue({ sourceKey: 'fulfillment-processing:request:ITEM_PROCESSING' }); expect(await createFboCompositionCharges(tx, input)).toBe(false); expect(tx.billingCharge.create).not.toHaveBeenCalled(); });
it('rejects incomplete facts and unknown variants before any write', async () => { const { tx, input } = fixture(); input.processedUnits = 4; await expect(createFboCompositionCharges(tx, input)).rejects.toThrow('фактического'); expect(tx.billingCharge.create).not.toHaveBeenCalled(); input.processedUnits = 3; input.packages[0].items[1].skuId = 'other'; await expect(createFboCompositionCharges(tx, input)).rejects.toThrow('не задан тариф'); expect(tx.billingCharge.create).not.toHaveBeenCalled(); });
